### ISSUE TITLE
Community input - moving to v1.0

### ISSUE THREAD

**Issue by rknell** [rknell/alfred#105]
Hey All!

We are at a point now where new features aren't being added and we are all pretty conscious of avoiding breaking changes.

I would like to merge https://github.com/rknell/alfred/pull/92 in, but it will potentially cause some users to need to upgrade their server environment. Since that could be a pretty difficult chance for some users I propose we use it as the change to move to v1.0

Does anyone have any thoughts or objections?

**Comment by d-markey** [comment]
No objection here :-)

**Comment by panzer-planet** [comment]
We have been using Alfred for one of our services in production for about a year. Currently it handles about 5k requests per day. 

The service is not trivial but has a very limited scope so we were keen to try something different. For our purpose it has been a fantastic experience. To my shame I can't comment on the topic at hand because I have not followed the project, but I have no objections. 

Our team is expanding in the near future so I hope to be more active in the community. At the moment we are on 0.1.4+5. We've not had any issues. 

I look forward to the 1.0 release. Thank you for all the hard work.

**Comment by rknell** [comment]
1.0 release on the way up today!
