### ISSUE TITLE
Need to be able to disable inbuilt error handling in favour of application level handing

### ISSUE THREAD

**Issue by moonlitknight** [rknell/alfred#114]
I am porting an existing REST API to Dart. Thus I am forced to replicate the existing error handling in my Dart app.
In the event of a JSON parse error, the existing API spec says "return status 400 with a response body containing as much information as possible regarding the error, for example, the character position of the error".

In my Dart/Alfred app, my exception handler is being triggered and the passed error object correctly contains the position of the offending JSON. However, when I try try res.send() the error message, I'm told that the headers have already been sent.

I believe this is discussed in #106 . The conclusion seems to be that this is the intended behaviour. As it stands, I'm unable to implement my API spec, so please could the intended behaviour be made overridable.

**Comment by rknell** [comment]
Hey - So it looks like you found a bug.

Ok, so first things first - you can easily override the error handling of uncaught errors - example here:
https://github.com/rknell/alfred/blob/master/example/example_error_handling.dart

Second - alfred only goes and sets the header if you return an object or if you have an uncaught error. So if you want to fully handle an error its really easy. Something like this:

```dart
import 'dart:convert';

import 'package:alfred/alfred.dart';
import 'package:alfred/src/alfred.dart';

void main() async {
  final app = Alfred();

  app.get('/', (req, res) {
    final badJSON = '{"name": "alfred",}';
    try {
      jsonDecode(badJSON);
    } catch (e, s) {
      res.statusCode = 400;
      res.send("""
      $e
      $s
      """);
    }
  });

  await app.listen();
}
```

**HOWEVER!** the body parser was getting in the way and setting its own headers and throwing everything off. So I have just made a breaking change that instead of it doing its thing, it now throws a "BodyParserException" which can be caught with a try/catch block. If you dont catch it - it should return as normal, but if you do catch it it may break some people app that is expecting to exit early. It wasn't very graceful so I think this is a change for the better.

I'll publish v1.1 with this change and you should be good to go from there. Some example code using the new method is here:

```dart
import 'package:alfred/alfred.dart';
import 'package:alfred/src/alfred.dart';

void main() async {
  final app = Alfred();

  app.post('/', (req, res) async {
    try {
      await req.bodyAsJsonMap;
    } on BodyParserException catch (e) {
      throw AlfredException(400, e.exception.toString());
    }

    return "JSON looks good yo.";
  });

  await app.listen();
}
```

**Comment by moonlitknight** [comment]
Many thanks for the rapid reply and fix (and great library).
When will you publish 1.1? 
I'm happy to pull from git and test and give feedback first if that's helpful.

Also, I suggest the example code with the new method you included above is so canonical it would be useful to promote it to the main documentation.

**Comment by rknell** [comment]
Sorry it should already be there. I'm not near the computer right now but
will see why it failed tomorrow. You can just develop against master if you
like for today - it's the same code that will be published tomorrow
