### ISSUE TITLE
100% Cpu Utilization Crashes

### ISSUE THREAD

**Issue by seceba** [rknell/alfred#116]
Hello,

I was actively using the backend, I was not having a problem, but yesterday we made a campaign and too many active visitors came to the application.

When the CPU usage is 100%, it locks up and the backend does not work. 
At the moment when the backend hangs, I observe 56 active connections, I think between 40-50 simultaneous connections, my backend freezes and does not recover again, I have to restart manually.

Is there any way to prevent this?

![Ekran Resmi 2023-02-20 12 47 46](https://user-images.githubusercontent.com/20662454/220072378-7644898a-b09c-4470-bfeb-7a9888847b37.png)

**Comment by seceba** [comment]
I think I solved my problem using isolate :) not sure but I ran 5 isolates as shown in the example.

Cpu never reached 100% again :) I don't know if it's relevant, next week we will do a campaign again and I will see.

However, in the current situation, 4gb ram 1core cpu can process up to 30 requests per second on a server.

**Comment by seceba** [comment]
Hi there, I found out what the problem was.
The bcrypt I use for encryption is really amazing.

I use it as round(11) and it uses 25% of my cpu for every verification or creation!

This is really crazy, I changed it to round(4) and now I'm getting 10x better performance, I don't understand why it's set to 11 by default.

This is just a souvenir, have a nice day :)

**Comment by rknell** [comment]
Hey @seceba 

Yeah what you have is less of an Alfred problem and more of a dart one. Not sure how you tracked down bCrypt as the culprit but its worthwhile getting used to using the dart debugging tools. The old classic ones I found easier to use. I had a similar problem with an early version of alfred in a production environment, and it turned out to be how I was sorting a list. A simple change by sorting it first and then using the sorted list instead of sorting it every time took my CPU usage down enormously.

I also discovered that I needed to use a StringBuffer when concatenating large strings instead of just doing string = string + "new text" etc as that used a HUGE amount of CPU.

If you haven't already do some profiling with your server. After optimization I ended up using only 10% cpu in a heavy use environment and it just stayed there no matter how much traffic I threw at it.
