### ISSUE TITLE
TODO x-alfred-route

### ISSUE THREAD

**Issue by felixblaschke** [rknell/alfred#14]
I looked for an approach on solving "route declaration passing" to retrieve the route parameters in the handlers. I see we have an architectural problem cause we are only relying on Dart:io's `HttpRequest` object instead of having an own "Context".

I would solve this by introducing Alfred's own `Request` and `Response` classes. Those are 1:1 mirroring the API of Dart:io classes. Additionally we can use the`Request` for transporting necessary information down the pipeline.

Example:

```dart
import 'package:alfred/alfred.dart';

class Request {
  /// HttpRequest instance from the dart:io library
  final HttpRequest nativeRequest;

  /// Route declaration that matches the current request
  HttpRoute? matchedRoute;

  Request({
    required this.nativeRequest,
  });
  
  // (!) From here everything copied and mapped from the dart:io library (!)

  /// The content length of the request body.
  ///
  /// If the size of the request body is not known in advance,
  /// this value is -1.
  int get contentLength => nativeRequest.contentLength;

  /// The method, such as 'GET' or 'POST', for the request.
  String get method => nativeRequest.method;

  /// The URI for the request.
  ///
  /// This provides access to the
  /// path and query string for the request.
  Uri get uri => nativeRequest.uri;

// ... rest of HttpRequest
}
```

This solution has on caveat. It raises your LOC counter 😄 .

**Comment by rknell** [comment]
Hey Felix,

I started off with this strategy but pretty quickly realised the main caveat isn't increasing the lines of code, but increasing the maintenance burden on the project - I don't actually give a damn about the lines of code personally, but its a good way to reduce the perceived risk in the community due to recent events.

It may not seem like much of a deal, but I want to have full feature parity for both the request and response object from dart:io. In this way if standards change etc, the dart / google team will be the ones who maintain the low level logic. As such I would want the class to implement the whole HttpRequest interface.

Right now, if dart:io was to change anything up, Alfred would just keep on rolling. However if we take this path, every time there is a tweak to the upstream HttpRequest class in the future, it would break the framework (because its an interface). Again not a huge deal as it just requires an adjustment on the class and dependencies, but since a core principle is keeping it small and maintainable by the community, it's why I didn't take this route and implemented the hacky workaround while I try and come up with a better solution.

If we were to go this way in the future, as the new class will implement the old class anyway, it shouldn't be a breaking change for any projects built against it. So not implementing it immediately isn't a huge loss as far as I am aware.

In my expressjs days I did as you suggested and created an auth object and attached it to the request so I could just call req.auth.userid etc. With another project I am currently running using Angel I instead opted for a simple function that was `getUserIdFromResponse(res)` and it would parse the request (usually a JWT) and return the user id. I could just call that with impunity because I would bump the user earlier on with an `isAuthenticated` middleware.

Which brings us to a fairly fundamental design choice about what a middleware should actually do - I'm thinking that the purpose of middleware in Alfred should really just be to manipulate or handle a http response. Anything more than that is up to the user. I think in the past we got away with making it more than it should be as we could just monkey patch objects to do as we pleased, but that might not be the best solution - and also isn't very dart like if we have a Map<String, dynamic> store and we are passing in things like an "Auth" class.

I think it might be worthwhile at some point to expose a stream of requests as they come in - this might just be a broadcast stream from the listen object, but also a stream of completed responses (it would be fired on the isDone future resolving) - something that sends through the request and response object for processing - such as logging or who knows what else.

Happy to keep this discussion going if there is something I am missing.

**Comment by rknell** [comment]
I've got an idea that fulfills both our requirements. Leave it with me

**Comment by felixblaschke** [comment]
I understand that it's a core requirement to solely rely on HttpRequest. And it's a good design choice.

I have another idea for accessing `Alfred` or Request-bound instances:

Alfred has a global map of all listening Alfred instances and maintains it:
```dart
class Alfred {
  static Map<int, Alfred> runningInstances = {}; // maps port to instance
  //...
}
```
Next Alfred tracks all running requests until they are fully resolved:
```dart
class Alfred {
  Map<HttpRequest, SomeMetaData> runningRequests = {};
  //...
}
```

Now we are able to access the metadata object from anywhere:
```dart
var port = req.connectionInfo?.localPort;
var metaObject = Alfred.runningInstances[port].runningRequests[req];
```

**Comment by rknell** [comment]
Yep! Pretty much what I did, however I wanted to break it out from alfred tracking the running requests and give a plugin developer the ability to tack something on. I think the API I implemented is actually pretty lightweight and straightforward.

You now have a store plugin! I don't love the function names (setStoreValue and getStoreValue), its a bit too verbose, but it works pretty well in my limited testing so far. If you can think of a better name then lets change it!
