### ISSUE TITLE
Improve middleware example

### ISSUE THREAD

**Issue by felixblaschke** [rknell/alfred#15]
In the README there is the following example:

```dart
import 'dart:async';
import 'dart:io';

import 'package:alfred/alfred.dart';

FutureOr exampleMiddlware(HttpRequest req, HttpResponse res) {
  // Do work
}

void main() async {
  final app = Alfred();
  app.all("/example/:id/:name", (req, res) {
    req.params["id"] != null; //true
    req.params["name"] != null; //true;
  }, middleware: [exampleMiddlware]);

  await app.listen(); //Listening on port 3000
}
```

- From reading this example the **order of execution** is not clear.
- The parameter extraction is irrelevant to the example.
- Maybe adding comments hinting what's executed first
- The parameter name `middleware` doesn't fit here, because it does not give a cue on execution order. Maybe introduce `before: [exampleMiddleware]` or `after: [exampleMiddleware]` for pre/postprocessing?

**Comment by rknell** [comment]
Agree this is hot garbage, will fix soon

**Comment by felixblaschke** [comment]
@rknell What's your opinion about a good API for middleware handling?

Currently we have two ways.

First (A) is using a route matcher to apply middleware, like:
```dart
app.all('*', cors);
```
Second (B) we have the `middleware` property on each `HttpRoute`:
```dart
app.get('some/route', (res, res) => 'response', middleware: [cors]);
```

I like the first method (A). It feels quite natural. Execution is in order of declaration. No need to change anything in my opinion.

The second method (B) lacks on wording. The term "middle" doesn't give any clue on execution order here. If we name it precisely it would be "middlewareExecutedBefore". But that is a very long name for a parameter. We can shorten it to "before". Question? If we name it "before", does the user get it, that we mean a middleware? Does he also expect an "after"? Also it's somehow reads strange.
```dart
app.get('some/route', (res, res) => 'response', before: [cors]);
```
Another name candidate that comes into my mind would be "applyBefore" or "useBefore". How does it look like?
```dart
app.get('some/route', (res, res) => 'response', useBefore: [cors]);
app.get('some/route', (res, res) => 'response', applyBefore: [cors]);
```
To me it reads better then "middleware" or "before" and is yet short enough. Any ideas?

**Comment by davidmartos96** [comment]
Have you guys thought about other ways to handle middlewares? Some examples are both express and Koa which use the `next` "pattern". The next method allows doing something at the end of all the handlers execution. See the implementation of the "responseTime" middleware in the Cascading section in the Koa docs: https://koajs.com/#introduction


Another kind of implementation is what shelf did, which involves a request, response and error handlers independently in the middleware. I haven't touched it too much to know the pros and cons though.
https://pub.dev/documentation/shelf/latest/shelf/createMiddleware.html

**Comment by rknell** [comment]
Hey @davidmartos96 ,

I was going to go with the "next" pattern when designing the system, but realised we could do away with it. There is a section in the readme which addresses it.

Because we can hook into if the request has been resolved - ie returned - we don't need an explicit next method, we can be smarter than that. The only issue is if you want to do something in another function after resolving it all. If you need to do that then you can listen for when requests complete and handle it there. I would not be surprised if we end up with an after at some point, but I'm not sure what the use case would be to create an after middleware?

**Comment by rknell** [comment]
@felixblaschke 

Before is probably clear enough. I usually use an onBefore type of convention when dealing with events and their timing, but before is short and succinct.

I used middlware because people coming from express would know where to find it. Middlewares are always executed before the function in my experience so I figured it would be assumed thats where it goes. If you want to change it to before thats fine, but maybe we should even deprecate it as it stands so we don't break anyones code, but also for new adopters they know to use "before" if they go looking for "middleware".

If I see a before I do expect there to be a corresponding after, which would be trivial to add in, but as I said above, what would the use case be? Surely if a user has some serious clean up logic they would extract that into a function and just handle that themselves?

**Comment by davidmartos96** [comment]
@rknell I don't think I'll need to hook into the middlewares finishing, but while reading I found the response time header use case in the Koa docs which I guess it could be useful for debugging and profiling purposes. I don't have other use cases in mind though.

**Comment by rknell** [comment]
For logging and performance purposes `Alfred.registerOnDoneListener` would be ideal. It fires when each response is resolved and passed on the details. While the callbacks do fire in order of registration, they don't wait for any async work to complete, so it won't be held up by something else busily cleaning up any resources.

**Comment by felixblaschke** [comment]
To summarize this. @rknell suggests the following algorithm:
- Process all matched routes until response has been closed
- Discard all further matching routes
- Optionally hook into `Alfred.registerOnDoneListener`

While this is simple, it's also intransparent to the user. Mostly he doesn't know when something does a `res.close`. To compensate this, we might want to integrate some kind of "visualisation/explaination on which route matched and got applied" to help him understand some cases.

For example this feels intuitive but has some pitfalls:
```dart
app.all('*', middleware1); // gets executed
app.get('some/resource', someResource()); // will close response
app.all('*', middleware2); // discarded / not executed
```

**Comment by felixblaschke** [comment]
And if we add a `after` for handle middleware afterwards. Won't they get discarded, too? Because most likely the response got closed.

**Comment by rknell** [comment]
Improved example but left middleware api as it for the moment
