### ISSUE TITLE
Scoped middlewares

### ISSUE THREAD

**Issue by davidmartos96** [rknell/alfred#24]
Is there any equivalent to Express use method or Shelf mount to handle requests and middlewares in a subroute?

Shelf has the concept of Routers which you can nest however you want.
Here is a simple example project from Creative Bracket in shelf.

Entrypoint of the server app:
https://github.com/graphicbeacon/dart_spa_boilerplate/blob/main/spa_server/bin/spa_server.dart

Then the user api router has a scoped middleware to check authorizations.
That's one of the reasons I propose using shelf under the hood like some other people suggested on Reddit 😅 But I've seen that you want to answer that question in more detail.

BTW, congrats on the project! It seems to be getting some traction 😄

**Comment by felixblaschke** [comment]
Thank you for the inspiration. I can't speak for @rknell but the routing api and middleware handling might get some overhaul before the final version.

I'll keeping an eye on doing stuff very simple while being open to flexibility.

**Comment by felixblaschke** [comment]
I was thinking about something like

```dart
var app = Alfred();
var subroute = app.routes('path/to', middlewareBefore: [SomeMiddleware()]);
subroute.get(':id', ...);
subroute.post(':id', ...);
subroute.routes('other/path').get('file', ...); // more cacading...
// etc.
```
Alfred then composes an absolute path for that.

**Comment by rknell** [comment]
Hey David,

It can absolutely do it - One of my projects has a concept like this already whereby I have a drop in crud model that sets up everything you need to manipulate a database table. This is great because it keeps it the logic contained within the route / class. I'll clean it up and add a route object to Alfred.

In regards to a middleware that applies to a route or even cascades to all subroutes, you can use a wildcard when defining the routes in app so

App.all("/auth/*",.....)
App.get("/auth/current user",....)

It will hit the wildcard before any subroutes, and if that doesn't resolve the request it will continue on.

Or you can define it on a per route group basis.

In regards to the logic changing I'm always open to improvements as they come in, and I do expect there might be a rewrite to the route logic at some point, but right now it's able to handle all of the requirements I have thrown at it as is. I don't expect significant changes to the syntax unless there is a good reason.

**Comment by davidmartos96** [comment]
@rknell Nice to hear! 
Once the library settles down a bit more in terms of API it would be great to have some examples with sessions, auth and database scenarios 😉

**Comment by rknell** [comment]
I'm going to close this out as Felix has put together a pull request which should address this

https://github.com/rknell/alfred/pull/27
