### ISSUE TITLE
Moving towards 0.1.0 final

### ISSUE THREAD

**Issue by rknell** [rknell/alfred#35]
Hey @felixblaschke,

Do you have anything on your roadmap thats got to be done before we push out 0.1.0?

I've put it into production now for a couple of apps but probably haven't done a huge amount of creative dev for weird edge cases. Ultimately I was able to replace a very large Angel app (large but using only the basics) and it hasn't had any troubles at all - this is pretty high traffic mission critical app.

I just want to be mindful about not changing the API too heavily so the community can really run with it, so is there anything you are itching to change or something you haven't raised yet?

**Comment by felixblaschke** [comment]
**Sounds good!** There is the middleware naming issue left, but we can go with it now, deprecate it when we have a solution and remove it at the latest on the 1.0.0 release.

You might want to check and maybe merge the PR on logging because it breaks a constructor parameter (`logRequests`). 

Other than that I don't see anything that puts the user-facing API upside down. We are still pre-final (< 1.0.0) and users adopting Alfred now should be aware of future changes. So feel free to release 0.1.0.

**Comment by davidmartos96** [comment]
What about multi isolate setup? Should that be in the 0.1.0 version? 
I don't know if I'm missing some complexity in the implementation, but when I played around with `shelf` it was as simple as instantiating the app on each isolate and then use the `shared=true` flag in the `HttpServer` from `dart:io`

**Comment by rknell** [comment]
Hey @davidmartos96 

I think we might park threading and isolates until a future release. They are absolutely on the roadmap but unfortunately its a part of the dart ecosystem which i'm not super familiar with, and as such I just don't know what I don't know at the moment. I would think it shouldn't change the packages API is any significant way though - I would hope the implementation is as simple as you described above, the user just opts in to (or out of) threading.

For 0.1.0 there have been a huge number of improvements and a few breaking changes to the api, so as long as it seems stable now - and I have had some time to put it into production - I think it would be a good point to release the update now that we can be sure it covers all bases.
