### ISSUE TITLE
Please look at pkg:shelf!

### ISSUE THREAD

**Issue by kevmoo** [rknell/alfred#44]
https://pub.dev/packages/shelf

We *really* encourage folks to build on top of `shelf`. It's designed to be more easily composed.

Let me know if you want to chat!

**Comment by rknell** [comment]
Hey Kevin,

Its been incredibly easy to build upon the core dart libraries to get to this stage, and i'd rather stick with something that comes built in. I have seen that you guys deprecated the http_server package the other day and replaced the docs to recommend shelf for "anything more" instead of http_server.

Is the current core functionality in dart:io about to be deprecated?

**Comment by kevmoo** [comment]
No! But dart:io HttpServer is not suited AT ALL for composition.

We plan to support pkg:shelf to the horizon. It's where we want to layer
the ecosystem.

**Comment by felixblaschke** [comment]
Hi @kevmoo,

thanks for reaching out to us.

From **my perspective** we have an **strong communication issue** regarding the support of HTTP in Dart. @rknell also addressed it in his answer: As a package developer it feels very **unsure** about Dart as a possible HTTP server platform. I **perceived** two major players (angel, aqueduct) throwing the towel. A few days later the Dart team's `http_server`, which seems to be the "one" with a working request body parser, went into deprecation. The shelf package (as a substitution) itself lacks such a body parser. Also shelf is not selling itself as "_the holy grail of the http dart future. Everyone should us as basic building block. Support to the horizon, etc._".

What we package developer need, is a vision, a commitment, or roadmap from the whole Dart team to further evolve HTTP server via **shelf** package. From **our point of view** it seems natural to think, that **shelf** is the next package, that gets dropped.

In my opinion these announcements shouldn't be in a comment of a GitHub issue. They should be somewhere on the dart website: "_Developer, if you plan to do http server with dart, build on shelf. We have great things in the pipeline!_"

I hope you understand my position and why we both are somehow confused. :-)

**Comment by felixblaschke** [comment]
@rknell I had good video chat with @kevmoo today, where he explained the importance of the shelf package and future plans in regards of the Dart server ecosystem.

If I remember correctly the set of packages shelf, shelf_router and shelf_static will form a base for the dart server-side ecosystem. He assured that shelf won't get dropped anytime soon, it's the opposite: shelf will get necessary features in the future, like http2 (if i resemble correctly).

I took a closer look at those packages and they overlap with Alfred's core feature set (routing / request handling). But I also noticed that shelf is harder to access, due to lack of examples and overview documentation (_"package puzzling to get the functionality you need"_). Kevmoo mentioned that this issue will also be addressed in the future.

**As a result of these new information, I will focus further work on the shelf stack.** Even if we can get some relevant user base on Alfred, it would lead to fragmentation and hurt the Dart ecosystem on the long run.

**Comment by kevmoo** [comment]
Low-level protocol work will likely happen in the core dart libraries.

These will be exposed to shelf transparently.

**Comment by rknell** [comment]
@felixblaschke Thanks for all your input to date, I really appreciate it, and respect your decision going forward.

In regards to shelf vs alfred, I think the composability is a mistake, and instead favour the extensibility we have implemented. A big factor that made me turn away from React Native was the removal of what I perceived as core packages from the base offering to let the community develop it. This led to a huge amount of maintenance and dependency hell, especially when something is broken.

I remember a week - literally a solid week - I went through when RN decided to change a part of their file system api, another package had a critical bug that was only compatible with the new version of RN but another one wasn't updated. This meant I needed to spend an entire week of dev to just fix upload an image to the server.

When i'm firing up a webserver I want 90% of the functions I require to be bundled up, compatible with each other, and just work out of the box. If I need some special functionality I want to be able to extend it in some way - which Alfred is excellent at IMO. I don't want to have to pull in a bunch of stuff just to serve a simple response.

Webservers, especially those for REST apis really aren't all that complex, all they need at a core:

1. Handle incoming connections
2. Handle routing
3. Handle body parsing
4. Handle responses

And 1 import should handle that at a minimum. I don't think they should have any opinion of the database or other components like authentication. I don't want to have to pull in a body parser or a router - I'm more interested in getting on with the job.

In the future I may well sub out dart:io for shelf under the hood, but given the above information I will continue to develop it, even if it is just an abstraction layer I can rely on to not break my current projects.

**Comment by subzero911** [comment]
I don't know how Shelf is looking under the hood, but it's terribly inconvenient, that's why I'm looking for alternative solutions, and find Alfred much better.
And who knows, maybe you will abandon Shelf (like Aqueduct developers did). Dart core libs unlikely will be discontinued.

**Comment by erf** [comment]
I'd like to throw in my opinion here.. I'm looking into using Dart more as a server, in addition to using it with Flutter. I have made a web app, starting with the simplest http package, but then moving over to Shelf, as is the go-to building block for web apps using Dart as per their [doc](https://dart.dev/tutorials/server/httpserver). I've just listening to @kevmoo talk about Shelf in the podcast Dart 101 [here](https://flutter101.dev/episodes/dart-backend-cloud-command-line-shelf-with-kevin-moore) and his commitment to Shelf and keep it a minimal composable framework to me is very clear. Kevin is product manager for Dart and has been for a while.

Alfred is very promising to me, it has lots of functionality you would need in a complete web server. Like you mention a body parser for parsing multipart, file uploads etc. I really wish this could be split up into composable Shelf middleware / packages. Because going forward i'd really like to use Shelf, as i see it as a very good abstraction to build on. I'm already using the shelf router, static package, web sockets and more, and i would really like to see the community, like yourself, contribute to this ecosystem. I'd like to use a larger framework, but only if built upon smaller composable packages using Shelf. I' rather not see a large custom framework splitting up the community and making it harder to make a choice. This is off course just my opinion and i thank you for the work on Alfred so far.

**Comment by erf** [comment]
@rknell just to make a point on composability, i think the Shelf package team has made it clear about keeping the package API as minimal as possible to encourage composability of the two concepts *handlers** and **middleware**. I think this is a good thing, as more people can work on extending the framework in a modular way. Even though in the rarest case that Shelf package would be "shelved" (sorry), i think the modular nature would still allow for other people to build on the same idea.

**Comment by rknell** [comment]
@erf you might want to check out the package shelf_plus

This is what @felixblaschke created after the comments above, has many of the features and structure of Alfred and is built entirely on shelf components. I think it fits the bill for what you are looking for

**Comment by rknell** [comment]
Also I haven't had a chance to listen to @kevmoo on Flutter 101 yet, but the point of handlers and middleware both exist and can be easily added to Alfred with another package. The reason for not splitting it off and creating a batteries not included ecosystem is I have had bad experiences with react native in particular relying on community support for core components and then inadvertently breaking them - leaving you in dependency hell.

So right now Alfred isn't great at handling large uploads as it relies on the old bodyparser package that stores the entire file in memory before returning it to the user, this would be a great example of a middleware / handler that could be created by the community and plugged in with about 2 lines of code. The package could either override the exisiting upload handler or create a middleware that could be attached to the route - so it doesn't mean you miss out by going with Alfred.

As I have stated before, at some point I may still sub out shelf under the hood anyway, but when this was created the official dart "how to write a server" used dart:io - and I love that it's bundled into the core without needing to add a new dependency.

**Comment by erf** [comment]
I think i understand but you could you not build a "batteries includes" framework based on Shelf packages?

I have not looked into Alfred much, but perhaps it's API could be tweaked to be similar to Shelf's building blocks or a convert function made.

I looked into shelf_plus by @felixblaschke and it looks interesting, but i'd prefer smaller packages, one per middleware, so i can pick and choose myself. E.g. A shelf_body_parser or shelf_jwt would be nice. Perhaps i will look into this myself later.

**Comment by rknell** [comment]
@erf I could build the batteries included framework upon shelf and I'm not ruling out moving to that one day but keeping the Alfred api the same - but shelf_plus is basically that.

From the sounds of it though what you are looking for is building your own stack from the ground up, and shelf is definitely the right choice if that's what you are after.

**Comment by erf** [comment]
@rknell Sounds good! Yes i guess i'd like to build things one step at the time. But i do like the Node frameworks like Express and Koa, where you can add third party middleware or roll your own. It seem Shelf (and also Alfred?) is very similar to that.

**Comment by subzero911** [comment]
I checked out shelf_plus, but it looks not production-ready yet. No Websockets, no ORM...

**Comment by davidmartos96** [comment]
@subzero911 As far as I know there is no framework agnostic ORM in Dart at the moment. Although I believe the conduit team (the rework of the Aqueduct framework) wants to extract the postgres/mysql ORM so that it can be used without the entire framework.
For websockets you could try https://pub.dev/packages/shelf_web_socket
