### ISSUE TITLE
Question about routing.

### ISSUE THREAD

**Issue by bubnenkoff** [rknell/alfred#79]
Currently I am serving folder in next way:
```
  app.get('/*', (req, res) {
    print('requested url: ${req.requestedUri}');
    return Directory('D:/site/');
  });
```

But I would like to be able send to browser folder content even if user will request not root, but:
/about, /news etc 

But with present code I am getting 404 if I am requesting for example /about.

I tried to do something like:
```
  app.get('/:name', (req, res) {
    print('requested url: ${req.requestedUri}');
    return Directory('D:/site/');
  });
```

But I am getting an error:
```
>dart run
Unhandled exception:
FormatException: Invalid empty scheme (at character 1)
:name
````

I know that I can do different handlers like: `/about` `/news` etc, but can I handle that such URL is requested like I do above? I want to serve static HTML page and pass inside it requested URL

**Comment by d-markey** [comment]
from [lib\src\type_handlers\directory_type_handler.dart](https://github.com/rknell/alfred/blob/master/lib/src/type_handlers/directory_type_handler.dart):

1. you MUST use a route with '*', so the first version is correct and the second one will not work

2. if a file matches the path supplied in the incoming request, it will be served, eg.
** GET /something ==> if file D:/site/something exists, it is served
** GET /home.html ==> if file D:/site/home.html exists, it is served
** GET /some/path/to/a/page.htm ==> if file D:/site/some/path/to/a/page.htm exists, it is served

3. otherwise, Alfred will look for an index in the supplied directory (eg. GET /something ==> send D:/site/something/index.html or D:/site/something/index.htm)

So the best bet is to place such an "index.html" file in your "/about" , "/news" etc directories.

**Comment by bubnenkoff** [comment]
@d-markey thanks for response!

I am trying to do next trick.
I have SPA stat use web-components. I have:
index.html file that include components depend on JS condition like:
<about-component></about-component>

I am doing switching them with JS.

I want to patch JS variable at dynamic with alfred and change current active page depend on user request to server.

For example if user requested: `/home` I will set (patch index.html):
```
globalThis.PAGES = {'home': true, 'price': false, 'docs': false, 'search': false },
```

If `/docs`:
```
globalThis.PAGES = {'home': false, 'price': false, 'docs': true, 'search': false },
```

But I want *single* endpoint for all static. Like I had shown. Is it's possible to do it with alfred?

I am doing this hack to emulate that page is exists on server.

I hope that I explained what I want. It it's possible?
