### ISSUE TITLE
Add support for route handlers 

### ISSUE THREAD

**Issue by alihassan143** [rknell/alfred#83]
please add route handler support so we can code the clean way currently all code have to be in one file that is not good

**Comment by alihassan143** [comment]
`app.use("/notes",NewRoute);`
like this in express you can refactor code easily and add multiple routes and connect them with eachother

**Comment by NathanDraco22** [comment]
Totally agree, waiting that feature too!
Meanwhile, you can use <part> and <part of> syntax to try to "solve" this feature lack.
But a routes handler is necessary

**Comment by rknell** [comment]
Hey guys,

agree it is nice and what i have done in the past for a larger project is created a class called AlfredRoute that had a list of routes as a required parameter and then iterated over those routes in the main() function to register them. It kept it clean and your certainly didn't need to have all the code in one file. The problem was this method didn't really handle recursion well so didn't built it in as a feature to the framework.

The other thing you should be doing is at the very least is breaking out each section of your code into its own handler classes and just registering the routes centrally.

So for example:

user_routes.dart
```dart
class UserRoutes {

    static login(req, res){
    ....
    }

    static currentUser(req, res){
    ....
    }

}
```

server.dart
```dart
import user_routes.dart;

class Server {
     start(){
        app.post('/users/login',UserRoutes.login);
        app.get('/users/currentUser',UserRoutes.currentUser);
     }
}
```

etc. The above is just pseudocode so it might need some tweaking, but you certainly shouldn't be putting your entire business logic in a single file.


However back to the feature request - I'm very open to doing an alfred route addition like express, it just needs to be fully featured, there is no point in doing it half baked, so routes need to be able to add routes and they need to be registered the whole way down.

**Comment by alihassan143** [comment]
yeah you are right feature have to be complete so please add this feature in the next update so we can use the alfred to our projects backend i love this package it have all the feature that needed to have in any server but just some little things are missing i hope you will implement them in the future

**Comment by d-markey** [comment]
Alternatively, you could also try out Pennyworth to handle route composition and mounting.

With Pennyworth, you can implement your service methods directly with strong types and provide annotations to specify URLs:

```math_service.dart```

```dart
@RestService('/', tags: ['MATH'])
class MathService extends NestedOpenedApi {
  MathService();

  @RestOperation(uri: '/add/:a:int/:b:int', summary: 'Returns a + b', output: int)
  Future<int> add(int a, int b) async {
    return a + b;
  }

  @RestOperation(uri: '/sqrt/:x:double', summary: 'Returns sqrt(x)', output: double)
  Future<double> sqrt(double x) async {
    if (x < 0) throw AlfredException(403, 'Square root of negative number');
    return math.sqrt(x);
  }

  @override
  List<OpenApiRoute> mount(
          NestedRoute parentRoute, OpenApiService openApiService) =>
      parentRoute.mount_MathService(this, openApiService);
}
``` 

This service is mounted on a specific mount point:

```math_api.dart```

```dart
class MathApi extends OpenedApiMountPoint {
  MathApi(NestedRoute parent) : mountPoint = parent,
        super([MathService()]);

  @override
  final NestedRoute mountPoint;
}
```

In your main program, you bind your API to the route segment you like:

```dart
void startServer() async {
  final app = Alfred();

  app.typeHandlers.insert(0, openApiTypeHandler);

  final openApiService = setupOpenApiDocumentation_v3(app);

  var apis = [
    MathApi(app.route('/math')),
    SwaggerApi(app.route('/dev/open-api'), openApiService, Directory('assets/swagger-ui-4.1.2/')),
  ];

  for (var api in apis) {
    openApiService.mount(api);
  }

  final server = await app.listen(8080);

  openApiService.addServer(server);

  app.printRoutes();
}
```

Pennyworth also comes with Swagger/OpenAPI integration so you can test/document your APIs directly from the code.

![image](https://user-images.githubusercontent.com/1548408/155012772-0c6b6836-8647-4efc-8f30-00297a8e0b57.png)

**Comment by d-markey** [comment]
Pennyworth is not released as a package yet. You can find more info here:

* https://github.com/d-markey/pennyworth
* https://github.com/d-markey/pennyworth_builder
* https://github.com/d-markey/pennyworth_sample

</shameless_plug>

**Comment by alihassan143** [comment]
@d-markey  great work i will try pennyworth and let you know

**Comment by rknell** [comment]
This is coming out in v1.0 which should be released today.
