### ISSUE TITLE
Database solutions

### ISSUE THREAD

**Issue by tomassasovsky** [rknell/alfred#86]
When releasing an app to Google Cloud Run, it seems like something like Hive or Isar is not supported... is there any way to work around this without having to switch to another DB solution?
If not, which DB solution could you recommend when deploying the app in Google Cloud Run?

**Comment by rknell** [comment]
Sorry I thought I had responded to this!

Personally I use mongo for just about everything. I have a SQL background but I find far less frustration with mongo day to day. But mongo isn't the be all and end all.

The problem with hive and other local solutions is the ephemeral storage - plus because you may have many processes spooled up as you scale they don't really scale with you - you would need to have another dedicated server with storage and only one process. So at the end of the day, I recommend any database solution that has its own hosted server, be it Mongo, Postgres, Redis etc.

For a small app that lives locally hive would be fine. I have used it a couple of times but got frustrated once or twice and ended up going with local file storage, but thats each to their own. I remember having a lot of trouble unit testing with hive and SQLite and since they were data heavy apps I needed to test that the queries were actually going to return data and not error out.
