### ISSUE TITLE
question: restart the server with the same port

### ISSUE THREAD

**Issue by yeikel16** [rknell/alfred#90]
I just started to test `Alfred` and I don't know if it is normal to change the port every time I restart the server, since when using the same port it throws an error: 
```bash
SocketException: Failed to create server socket (OS Error: Only one use of each socket address (protocol/network address/port) is allowed, errno = 10048), address = 0.0.0.0, port = 1023
```
I'm using:
`alfred: ^0.1.5+3`
```
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (2 weeks ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
```

**Comment by rknell** [comment]
Hey sorry didn't realise I forgot to get back to you. Its probably too late but for anyone else who comes across this its not normal - for some reason you still have the server process running in the background which is why you are getting this error. Do diagnose it I would need to see how you are launching the server.

Personally I use Android Studio for most of my dart dev, so I either create a dart run task so I can hit play up the top (which manages this and closes the old process) or if I am using the command line during dev its `dart server.dart` etc and then use control+c on mac (not sure of the windows command) to close it down.

If you are on a linux box and are adding an ampersand at the end of the command ie: `dart server.dart &` then you are daemonsing the process and you will need to find the PID and use a kill command.
