### ISSUE TITLE
Server Sent Events + alfred

### ISSUE THREAD

**Issue by bubnenkoff** [rknell/alfred#98]
Could you provide example of using SSE with alfred.
I can't understand how to make them work together https://github.com/dart-lang/sse/blob/master/example/server.dart

**Comment by rknell** [comment]
Hey @bubnenkoff ,

Sorry I haven't used SSE. Since its a plugin for shelf this is probably the first time I have had a real argument to migrate the underlying framework to shelf so you can use it with alfred.

I can probably give you an example for websockets but right now im busy setting up this distillery and just not doing much with Alfred day to day though will be again soon. I'll comment on the websocket issue and close this one as its not yet compatible, but I think the next time I am really digging in its time to migrate to shelf under the hood and I will come back to it when thats done.
